name: Haskell CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Haskell (GHC and Cabal)
        uses: haskell/actions/setup@v2
        with:
          ghc-version: latest
          cabal-version: latest

      - name: Cache Cabal store
        uses: actions/cache@v4
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-cabal-

      - name: Update package index
        run: cabal update

      - name: Build
        run: cabal build --enable-tests

      - name: Test
        run: cabal test --test-show-details=direct
