name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up GHC
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.12.2'
    
    - name: Install dependencies
      run: |
        cabal update
        cabal install --global hspec
    
    - name: Build and test
      run: |
        make test
    
    - name: Build executable
      run: |
        make build
